layout: sidebar
style: light
# Name of website
title: Eight Portions

# Short description of your site
description: "Yutong's personal website"


name: Yutong Xie
theme: jekyll-theme-cayman

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/